# -*- coding: utf-8 -*-
"""
/***************************************************************************
 entf_besch
                                 A QGIS plugin
 Bescheinigung nach Entfernung
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-16
        copyright            : (C) 2021 by Marius Schaefer
        email                : marius.schaefer@kreis-unna.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load entf_besch class from file entf_besch.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .entf_besch import entf_besch
    return entf_besch(iface)
